<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="1.1.1" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.0" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
        <PackageVersion Include="Yozian.Extension" Version="2.6.7" />
        <PackageVersion Include="nunit" Version="3.14.0" />
        <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
    </ItemGroup>

</Project>
